### ISSUE TITLE
environment.yml assumed to be in $HOME at second try

### ISSUE THREAD

**Issue by knutfrode** [bast/singularity-conda#5]
Hi!

First time I tried this package (yesterday, on Fram server), it worked fine.
However, at second try, with new project in another folder, I (as well as another user) get the error message below. 
It seems that something is cached somewhere, insisting that from second time, `environment.yml` is assumed to be in `$HOME`, which is not generally true (`~/work/kfd` in this case).

```
[knutfd@login-2.FRAM ~/work/kfd]$ ./conda.sif 
EnvironmentFileNotFound: '/cluster/home/knutfd/environment.yml' file not found
EnvironmentLocationNotFound: Not a conda environment: /cluster/home/knutfd/environment
```

**Comment by bast** [comment]
Thanks for reporting this! I am looking into it.

**Comment by bast** [comment]
I tried it on my home computer and there this problem did not appear. I will try to reproduce it on Fram.

**Comment by bast** [comment]
Hmm... I cannot reproduce it on Fram either. Thinking what this might be ...

**Comment by bast** [comment]
I can't reproduce the problem there either. I suspect that the container inherits something from the host environment which confuses it.

Can you test whether this works on repeated calls:
```
$ env -i ./conda.sif python
```

This will run the container in a clean environment.

If this works, then we should try to identify which setting gets passed on so that I can fix the container for that.

**Comment by bast** [comment]
With the change #6 it might now just work and maybe/hopefully the problem is gone. Please let me know if the problem is still there and then we can look at environment variables in detail.

**Comment by bast** [comment]
I think I reproduced the same issue. Working on it ...

**Comment by bast** [comment]
To get this to work I needed to do this:
```bash
$ env SINGULARITY_BIND="/cluster" ./conda.sif python
```
I also added this to the README.

I think this solves it but please re-open if not.
